enum WsEvent {
  POST_REACTION = "POST_REACTION",
  COMMENT_REACTION = "COMMENT_REACTION",
  COMMENT_CREATED = "COMMENT_CREATED",
  COMMENT_UPDATED = "COMMENT_UPDATED",
  COMMENT_DELETED = "COMMENT_DELETED",
  POST_CREATED = "POST_CREATED",
  POST_UPDATED = "POST_UPDATED",
  POST_DELETED = "POST_DELETED",
}

export default WsEvent